version: "3.5"

services:
  ####################### Database #######################
  database:
    image: coevent:database
    container_name: ce-database
    profiles:
      - "core"
    restart: on-failure:1
    build:
      context: db/mssql
    env_file:
      - db/mssql/.env
    ports:
      - ${DATABASE_PORT:-10000}:1433
    volumes:
      - ce-database-data:/var/opt/mssql
    networks:
      - ce

  ####################### Keycloak #######################
  keycloak:
    image: coevent:keycloak
    restart: on-failure:1
    container_name: ce-keycloak
    profiles:
      - "disable"
    build:
      context: ./auth/keycloak
    env_file:
      - auth/keycloak/.env
    volumes:
      - ./auth/keycloak/config/realm-export.json:/tmp/realm-export.json
    ports:
      - ${KEYCLOAK_PORT:-10006}:8080
    depends_on:
      - database
    networks:
      - ce


  ####################### SEQ - Logs #######################
  seq:
    image: coevent:seq
    container_name: ce-seq
    profiles:
      - "utility"
    stdin_open: true
    restart: on-failure:1
    build:
      context: tools/seq
    volumes:
      - ce-seq-data:/data
    ports:
      - ${SEQ_HTTP_PORT:-10006}:80
      - ${SEQ_INJEST_PORT:-10007}:5341
    env_file: ./tools/seq/.env
    networks:
      - ce

  ####################### API #######################
  api:
    image: coevent:api
    container_name: ce-api
    profiles:
      - "core"
    restart: on-failure:1
    build:
      context: api
      args:
        BUILD_CONFIGURATION: Debug
    env_file: api/.env
    ports:
      - ${API_HTTP_PORT:-10002}:80
      - ${API_HTTPS_PORT:-10003}:443
    depends_on:
      - database
    networks:
      - ce

  ####################### APP #######################
  app:
    image: coevent:app
    container_name: ce-app
    profiles:
      - "core"
    stdin_open: true
    tty: true
    restart: on-failure:1
    build:
      context: app
    volumes:
      - ./app/src:/usr/app/src
      - ./app/public:/usr/app/public
      - ce-app-node-cache:/usr/app/node_modules
    ports:
      - ${APP_HTTP_PORT:-10004}:3000
      - ${APP_HTTPS_PORT:-10005}:443
    depends_on:
      - api
    env_file: ./app/.env
    networks:
      - ce

####################### Networks Definition #######################
networks:
  ce:
    name: ce-net
    driver: bridge

####################### Volumes Definition #######################
volumes:
  ce-database-data:
    name: ce-database-data
  ce-seq-data:
    name: ce-seq-data
  ce-app-node-cache:
    name: ce-app-node-cache
